kind: pipeline
type: docker
name: ARtisticPipeline

trigger:
    event:
        - push

steps:
- name: api-build
  image: androidsdk/android-30
  commands:
  - cd Source/AR_tistic
  - ./gradlew api:assemble

- name: app-build
  image: androidsdk/android-30
  commands:
  - cd Source/AR_tistic
  - ./gradlew :app:assembleDebug

- name: code analysis
  image: androidsdk/android-30
  settings:
      sources: ./Source
  commands:
  - cd Source/AR_tistic
  - ./gradlew sonarqube -Dsonar.projectKey=ARTeam-SAE-3.01 -Dsonar.host.url=https://codefirst.iut.uca.fr/sonar/ -Dsonar.login=$${SONAR_TOKEN}
  secrets: [sonar_token]
  settings:
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token:
        from_secret: SONAR_TOKEN
  depends_on: [ app-build, api-build]

