kind: pipeline
type: docker
name: ARtisticPipeline

trigger:
    event:
        - push

steps:

- name: app-build
  image: androidsdk/android-31
  commands:
  - cd Source/AR_tistic
  - ./gradlew :app:assembleDebug
  
- name: api-build
  image: androidsdk/android-31
  commands:
  - cd Source/AR_tistic
  - ./gradlew stub:assemble
  - ./gradlew classLib:assemble
  - ./gradlew classLibDTO:assemble
  - ./gradlew dataContract:assemble
  - ./gradlew api:assemble
  depends_on: [ app-build ]

- name: code analysis
  image: androidsdk/android-31
  environment:
      SONAR_TOKEN:
        from_secret: sonar_token
  settings:
      sources: ./Source
  commands:
  - cd Source/AR_tistic
  - ./gradlew sonarqube -Dsonar.projectKey=ARTeam-SAE-3.01 -Dsonar.host.url=https://codefirst.iut.uca.fr/sonar -Dsonar.login=$${SONAR_TOKEN}
  depends_on: [ app-build, api-build]

- name: deploy-container-mysql
  image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
  environment:
      IMAGENAME: mariadb:10
      CONTAINERNAME: mysql
      COMMAND: create
      # OVERWRITE: true
      PRIVATE: true
      CODEFIRST_CLIENTDRONE_ENV_MARIADB_ROOT_PASSWORD:    
        from_secret: db_root_password
      CODEFIRST_CLIENTDRONE_ENV_MARIADB_DATABASE:
        from_secret: db_database
      CODEFIRST_CLIENTDRONE_ENV_MARIADB_USER:
        from_secret: db_user
      CODEFIRST_CLIENTDRONE_ENV_MARIADB_PASSWORD:
        from_secret: db_password
  
- name: container-api
  image: plugins/docker
  settings:
    dockerfile: ./Source/AR_tistic/api/src/main/java/com/example/api/Dockerfile
    context: ./Source/AR_tistic
    registry: hub.codefirst.iut.uca.fr
    repo: hub.codefirst.iut.uca.fr/axel.de_la_fuente/api-artistic
    username:
      from_secret: secret-registry-username
    password:
      from_secret: secret-registry-password
  depends_on: [ api-build ]
  
- name: deploy-api-containers
  image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
  environment:
    IMAGENAME: hub.codefirst.iut.uca.fr/axel.de_la_fuente/api-artistic:latest
    CONTAINERNAME: api-artistic
    COMMAND: create
    # OVERWRITE: true
  depends_on: [ container-api ]
