kind: pipeline
type: docker
name: ARtisticPipeline

trigger:
    event:
        - push

steps:
- name: api-build
  image: androidsdk/android-30
  commands:
  - cd Source/AR_tistic
  - ./gradlew api:assemble

- name: app-build
  image: androidsdk/android-30
  commands:
  - cd Source/AR_tistic
  - ./gradlew :app:assembleDebug

- name: code analysis
  image: androidsdk/android-30
  settings:
      sources: ./Source
  commands:
  - cd Source/AR_tistic
  - ./gradlew sonarqube -Dsonar.projectKey=ARTeam-SAE-3.01 -Dsonar.host.url=https://codefirst.iut.uca.fr/sonar -Dsonar.login=sqp_5e415651f882560d743bd044904d93507c89e5b5
  secrets: [SONAR_TOKEN]
  depends_on: [ app-build, api-build]

