kind: pipeline
type: docker
name: ARtisticPipeline

trigger:
    event:
        - push

steps:
- name: api-build
  image: androidsdk/android-30
  commands:
  - cd Source/AR_tistic
  - ./gradlew api:assemble

- name: app-build
  image: androidsdk/android-30
  commands:
  - cd Source/AR_tistic
  - ./gradlew :app:assembleDebug

- name: code analysis
  image: aosapps/drone-sonar-plugin
  settings:
      sonar_login:
        from_secret: sonar_login2
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
      sources: ./Source
  depends_on: [ app-build, api-build]