kind: pipeline
type: docker
name: ARtisticCI

trigger:
    event:
        - push

steps:
  
- name: build & analysis
  image: androidsdk/android-31
  environment:
      SONAR_TOKEN:
        from_secret: sonar_token
  settings:
      sources: ./Source
  commands:
  - cd Source/AR_tistic
  - ./gradlew --no-daemon :app:assembleDebug stub:assemble classLib:assemble classLibDTO:assemble dataContract:assemble database:assemble api:assemble sonarqube -Dsonar.projectKey=ARTeam-SAE-3.01 -Dsonar.host.url=https://codefirst.iut.uca.fr/sonar -Dsonar.login=$${SONAR_TOKEN} 

---
kind: pipeline
type: docker
name: ARtisticCD

trigger:
    event:
        - push

steps:

- name: deploy-container-mysql
  image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
  environment:
      IMAGENAME: mariadb:10
      CONTAINERNAME: mysql
      COMMAND: create
      # OVERWRITE: true
      PRIVATE: true
      CODEFIRST_CLIENTDRONE_ENV_MARIADB_ROOT_PASSWORD:    
        from_secret: db_root_password
      CODEFIRST_CLIENTDRONE_ENV_MARIADB_DATABASE:
        from_secret: db_database
      CODEFIRST_CLIENTDRONE_ENV_MARIADB_USER:
        from_secret: db_user
      CODEFIRST_CLIENTDRONE_ENV_MARIADB_PASSWORD:
        from_secret: db_password
      ADMINS: axelde_la_fuente
  
- name: container-api
  image: plugins/docker
  settings:
    dockerfile: ./Source/AR_tistic/api/src/main/java/com/example/api/Dockerfile
    context: ./Source/AR_tistic
    registry: hub.codefirst.iut.uca.fr
    repo: hub.codefirst.iut.uca.fr/axel.de_la_fuente/api-artistic
    username:
      from_secret: secret-registry-username
    password:
      from_secret: secret-registry-password
  
- name: deploy-api-containers
  image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-dockerproxy-clientdrone:latest
  environment:
    IMAGENAME: hub.codefirst.iut.uca.fr/axel.de_la_fuente/api-artistic:latest
    CONTAINERNAME: api-artistic
    COMMAND: create
    OVERWRITE: true
    CODEFIRST_CLIENTDRONE_ENV_DB_ROOT_PASSWORD:    
        from_secret: db_root_password
    CODEFIRST_CLIENTDRONE_ENV_DB_SERVER:
      from_secret: db_server
    CODEFIRST_CLIENTDRONE_ENV_DB_USER:
      from_secret: db_user
    CODEFIRST_CLIENTDRONE_ENV_DB_PASSWORD:
      from_secret: db_password
    CODEFIRST_CLIENTDRONE_ENV_DB_DATABASE:
      from_secret: db_database
    ADMINS: axelde_la_fuente
  depends_on: 
    - container-api

---
kind: pipeline
type: docker
name: ARtisticDoc

trigger:
    event: 
      - push

steps:

- name: generate-and-deploy-docs
  image: hub.codefirst.iut.uca.fr/thomas.bellembois/codefirst-docdeployer
  volumes:
    - name: docs
      path: /docs
  commands:
    - /entrypoint.sh
  when:
      branch:
        - master

volumes:
- name: docs
  temp: {}