kind: pipeline
type: docker
name: ARtisticPipeline

trigger:
    event:
        - push

steps:
- name: api-build
  image: androidsdk/android-30
  commands:
  - cd Source/AR_tistic
  - ./gradlew api:assemble

- name: app-build
  image: androidsdk/android-30
  commands:
  - cd Source/AR_tistic
  - ./gradlew :app:assembleDebug

- name: code analysis
  image: aosapps/drone-sonar-plugin
  settings:
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token: 96864ed9ef8d6343007881fc9ef30eb70eaf846d
      level: DEBUG
      sources: .
  depends_on: [ app-build ]
